sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '2.3'
services:
  - mongodb
  - redis

script: make test-cov
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
